# Generated by Django 4.2.4 on 2023-10-08 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address_line_1',
            new_name='addres_line_1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address_line_2',
            new_name='addres_line_2',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
